id: maixcam_test
name: 视觉测试
version: 1.1.0
author: cfyh
icon: ''
desc: 视觉模块测试工程
files:
  - module\__init__.py
  - module\camera.py
  - module\uart.py
  - vision\__init__.py
  - vision\digit.py
  - vision\line.py
  - vision\rectangle.py
  - app.yaml
  - config.py
  - main.py
